# ruff: noqa: E501

import enum


class StickersEnum(enum.Enum):

    KAMILA_AUTH = "CAACAgIAAxkBAAEM5llm-pT1LUzQTliT_82bt8o0pNkKywACslsAAjXW2Us8EmzPkc3X9jYE"
    KAMILA_ONBOARDING = "CAACAgIAAxkBAAEM5ltm-pUX_OQwGmMNqaSoUS4N088AATAAAoZcAAKUZtlLCvEwIlDYVc42BA"
    KAMILA_MAIN = "CAACAgIAAxkBAAEM5l1m-pUwD9gcGRrbfEYLjkEx5i8SoAAC308AAowz2Es5uQABIwVEcv82BA"
    KAMILA_LANGUAGE_TEST = "CAACAgIAAxkBAAEM5l9m-pVBt4X_CinVXDVP-LCZAQY5XgACQFsAAhG70EuT1HhJmq8GhzYE"
    KAMILA_START_IF_NOT_PAID = "CAACAgIAAxkBAAEM5mFm-pVKnMzWyEDTAo61VIncy5MgqQAC-FYAArHw0EvWOu-2bL8YUDYE"
    KAMILA_IF_NOT_PAID = "CAACAgIAAxkBAAEM5mNm-pVW_tOmzcvA0kUQqMHR-zRcwQACJF4AAqOE0Usf1c7iVMyrwjYE"
    KAMILA_LANGUAGE_TEST_RESULT = "CAACAgIAAxkBAAEM5mVm-pVgdSSx8_rzbf-e7mVsOJdTIAACM1MAAmBl2EtUrz-Z5VmDUTYE"
    KAMILA_FIRST_DIALOG = "CAACAgIAAxkBAAEM5mdm-pVrBNh_RX0BfxMUBtg5-hPrgAAC6VMAAo1V2UtwL-LfY4cbzzYE"
    KAMILA_MY_TOPIC = "CAACAgIAAxkBAAEM5mlm-pVyd0a9zlmMPKFGObJfO6Jp8gAC9FUAAvW62Uve47WNObOlezYE"
    KAMILA_SECOND_DIALOGUE = "CAACAgIAAxkBAAEM5mtm-pV58f3jJCjxmynxPfwCaHQiyAACgVoAAtvq2EtcJZJ52t-Y7zYE"
    KAMILA_TRANSLATE = "CAACAgIAAxkBAAEM5m1m-pWCeRfa2dkOv6c4PcfkLd5BLAACclgAAmGt0EszJxvDzy4NOTYE"
    KAMILA_DONE = "CAACAgIAAxkBAAEM6OBm_Tg7HmTUO4BhmmHPR0o4Oq0fgwAC3VoAAui86EsKoUq5xEKvSDYE"
