"""add table AITable

Revision ID: 1875ebf3eb96
Revises: 4a74b983a84b
Create Date: 2024-09-22 10:19:12.565263

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1875ebf3eb96"
down_revision: Union[str, None] = "4a74b983a84b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gpt_api_key", sa.String(), nullable=False),
        sa.Column("elevenlabs_api_key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai")
    # ### end Alembic commands ###
