"""create table lang_test

Revision ID: 4a74b983a84b
Revises: c5ddcde764e2
Create Date: 2024-09-21 16:27:46.474703

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a74b983a84b"
down_revision: Union[str, None] = "c5ddcde764e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lang_tests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tg_id", sa.String(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("current_question", sa.JSON(), nullable=True),
        sa.Column("replies", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lang_tests")
    # ### end Alembic commands ###
