"""add context

Revision ID: ff90d7b2aa3e
Revises: 1875ebf3eb96
Create Date: 2024-09-25 14:50:23.737811

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff90d7b2aa3e"
down_revision: Union[str, None] = "1875ebf3eb96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dialogs", sa.Column("tg_id", sa.String(), nullable=False))
    op.add_column("dialogs", sa.Column("context", sa.JSON(), nullable=False))
    op.add_column("dialogs", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("dialogs", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dialogs", "updated_at")
    op.drop_column("dialogs", "created_at")
    op.drop_column("dialogs", "context")
    op.drop_column("dialogs", "tg_id")
    # ### end Alembic commands ###
