"""new enum module

Revision ID: 0741d89c3eef
Revises: 33fa25447107
Create Date: 2024-10-18 18:14:24.278048

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0741d89c3eef"
down_revision: Union[str, None] = "33fa25447107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE module_enum ADD VALUE 'SENDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            """
            CREATE TYPE module_enum_new AS ENUM
            ('START', 'AUTH', 'ONBOARDING', 'MENU',
            'TRANSLATE', 'DIALOGS', 'LANG_TEST');
            """,
        )
        op.execute("DELETE FROM audit WHERE module = 'SENDING';")
        op.execute(
            """
            ALTER TABLE audit
                ALTER COLUMN module TYPE module_enum_new
                    USING (module::text::module_enum_new);""",
        )
        op.execute("DROP TYPE module_enum;")
        op.execute("ALTER TYPE module_enum_new RENAME TO module_enum;")
    # ### end Alembic commands ###
