"""create audit table

Revision ID: a641da50afca
Revises: a981e49c7d64
Create Date: 2024-10-03 15:10:10.594985

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a641da50afca"
down_revision: Union[str, None] = "a981e49c7d64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tg_id", sa.String(), nullable=False),
        sa.Column(
            "module",
            sa.Enum(
                "START",
                "AUTH",
                "ONBOARDING",
                "MENU",
                "TRANSLATE",
                "DIALOGS",
                "LANG_TEST",
                name="module_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "BOT_SENT",
                "USER_SENT",
                "USER_PUSH",
                "SHARE_CONTACT",
                name="action_enum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit")
    # ### end Alembic commands ###
